# Generated by Django 4.1.3 on 2022-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pais',
            field=models.CharField(default='coño', max_length=120),
        ),
    ]
